FROM centos
RUN yum install -y pciutils \
	&& yum install -y tcpdump \
	&& yum install -y nginx \
	&& yum install -y wget \
	&& yum install -y httpd-tools \
	&& yum install -y net-tools 

WORKDIR /home/ych
